# -*- coding: utf-8 -*-
"""485-final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L90k1PDhFR-PKBAt8lXPn7Sna75Hl7tO
"""

!pip install openai

import openai

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="",
)

def generate(prompt):
    """
    Initializes a chat with GPT-4 and sends a prompt to get a response.

    Args:
    prompt (str): The prompt or question to send to GPT-4.

    Returns:
    str: The content of GPT-4's response.
    """
    try:
        openai.api_key = ''
        completion = client.chat.completions.create(
            model="text-davinci-003",  #model="gpt-4"
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
        )
        return completion.choices[0].message.content
    except Exception as e:
        return str(e)

text = "Language models are not yet good enough to be reliable thinking partners. Their frequent hallucinations make it difficult to know if their factual claims are valid. They are unreliable narrators until proven otherwise. If you ask them for references, they'll happily generate very real sounding journal names, author names, and URLs. None of which exist. Until we drastically improve their ability to respond with accurate factual information and real citations, we can't treat them as a reliable source of knowledge."

prompt = f"Assess the emotional impact of this narrative. Suggest changes to enhance its pathos and emotional appeal:\n\n{text}"

result = generate(prompt)
print(result)
